export const cars = [
  {
    id: '1',
    name: 'Mazda CX5 2.2 Diesel',
    brand: "Subaru",
    price: 2950000,
    conditionScore: '4.5/5',
    bodyType: "SUV",
    year: 2018,
    location: 'Highseas, enroute Mombasa',
    availability: 'Available',
    drive: '4WD',
    mileAge: '88,000 KM',
    engineSize: '2200 CC',
    fuelType: 'Diesel',
    horsePower: '175 Hp',
    transmission: 'Automatic',
    torque: '420 Nm',
    acceleration: '9.5 Secs',
    description:
      'Currently on highseas enroute to Port of Mombasa. Estimated arrival Nairobi, date 26th February. Low mileage. Well equipped model. Reserve early and get preferential number plate.',
    images: [
      '/showroom.jpg',
      '/images/hero1.png',
      '/showroom.jpg',
      '/images/hero2.png',
      '/showroom.jpg',
    ],
  },
  {
    id: '2',
    name: 'Mazda CX5 2.2 Diesel',
    brand: "Sedan",
    price: 3950000,
    seller: 'Private Seller',
    conditionScore: '4.5/5',
    bodyType: "Sedan",
    year: 2018,
    location: 'Highseas, enroute Mombasa',
    availability: 'Available',
    drive: '4WD',
    mileAge: '88,000 KM',
    engineSize: '2200 CC',
    fuelType: 'Diesel',
    horsePower: '175 Hp',
    transmission: 'Automatic',
    torque: '420 Nm',
    acceleration: '9.5 Secs',
    description:
      'Currently on highseas enroute to Port of Mombasa. Estimated arrival Nairobi, date 26th February. Low mileage. Well equipped model. Reserve early and get preferential number plate.',
    images: [
      '/images/hero1.png',
      '/images/mazda-cx5-2.jpg',
      '/images/mazda-cx5-3.jpg',
    ],
  },
  // Add more vehicles as needed
];